### ISSUE TITLE
Could move the sample automation into it's own file

### ISSUE THREAD

**Issue by ckabalan** [ckabalan/bitwarden-attachment-exporter#4]
Making it easier for someone to run, maybe improve it by checking for required tools and displaying errors if not installed...

**Comment by peterrus** [comment]
Hi @ckabalan, I added #8. Let me know what you think if you can find some time.

**Comment by peterrus** [comment]
Shall we close this one @ckabalan? Of leave it open to implement the dependency checks? (Maybe rename the issue in that case)
